export const LEADERBOARD_LABELS = {
  pageTitle: 'Leaderboards',
  createLeaderboard: 'New Leaderboard',
  editLeaderboard: 'Edit Leaderboard',
  deleteLeaderboard: 'Delete Leaderboard',
  leaderboardName: 'Leaderboard Name',
  description: 'Description',
  selectRaces: 'Select Races',
  selectRacesSubtitle: 'Only finished races can be added to a leaderboard',
  noLeaderboards: 'No leaderboards yet',
  noLeaderboardsSubtitle: 'Combine finished races to build a championship standing',
  noFinishedRaces: 'No finished races available',
  noFinishedRacesSubtitle: 'Finish at least one race before creating a leaderboard',
  deleteConfirmTitle: 'Delete Leaderboard',
  deleteConfirmMessage: 'Are you sure you want to delete this leaderboard?',
  standings: 'Standings',
  racesIncluded: 'Races Included',
  driver: 'Driver',
  totalPoints: 'Total Pts',
  createSuccess: 'Leaderboard created successfully',
  deleteSuccess: 'Leaderboard deleted successfully',
} as const
