import { TypographyVariantsOptions } from '@mui/material/styles'

export const TYPOGRAPHY_VARIANTS: TypographyVariantsOptions = {
  fontFamily: '"Barlow", "Helvetica Neue", Arial, sans-serif',
  h1: {
    fontFamily: '"Bebas Neue", Arial, sans-serif',
    fontSize: '3rem',
    fontWeight: 400,
    letterSpacing: '0.05em',
    lineHeight: 1,
  },
  h2: {
    fontFamily: '"Bebas Neue", Arial, sans-serif',
    fontSize: '2.25rem',
    fontWeight: 400,
    letterSpacing: '0.04em',
    lineHeight: 1.1,
  },
  h3: {
    fontFamily: '"Bebas Neue", Arial, sans-serif',
    fontSize: '1.75rem',
    fontWeight: 400,
    letterSpacing: '0.03em',
    lineHeight: 1.2,
  },
  h4: {
    fontFamily: '"Barlow Condensed", Arial, sans-serif',
    fontSize: '1.375rem',
    fontWeight: 700,
    letterSpacing: '0.02em',
    lineHeight: 1.3,
  },
  h5: {
    fontFamily: '"Barlow Condensed", Arial, sans-serif',
    fontSize: '1.125rem',
    fontWeight: 700,
    letterSpacing: '0.01em',
    lineHeight: 1.4,
  },
  h6: {
    fontFamily: '"Barlow Condensed", Arial, sans-serif',
    fontSize: '1rem',
    fontWeight: 700,
    letterSpacing: '0.01em',
    lineHeight: 1.4,
  },
  body1: {
    fontFamily: '"Barlow", Arial, sans-serif',
    fontSize: '1rem',
    fontWeight: 400,
    lineHeight: 1.6,
  },
  body2: {
    fontFamily: '"Barlow", Arial, sans-serif',
    fontSize: '0.875rem',
    fontWeight: 400,
    lineHeight: 1.5,
  },
  subtitle1: {
    fontFamily: '"Barlow Condensed", Arial, sans-serif',
    fontSize: '1rem',
    fontWeight: 600,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
    lineHeight: 1.4,
  },
  subtitle2: {
    fontFamily: '"Barlow Condensed", Arial, sans-serif',
    fontSize: '0.8125rem',
    fontWeight: 600,
    letterSpacing: '0.1em',
    textTransform: 'uppercase' as const,
    lineHeight: 1.4,
  },
  caption: {
    fontFamily: '"Barlow", Arial, sans-serif',
    fontSize: '0.75rem',
    fontWeight: 400,
    color: '#9999AA',
    lineHeight: 1.4,
  },
  overline: {
    fontFamily: '"Barlow Condensed", Arial, sans-serif',
    fontSize: '0.6875rem',
    fontWeight: 700,
    letterSpacing: '0.15em',
    textTransform: 'uppercase' as const,
    lineHeight: 1.4,
  },
  button: {
    fontFamily: '"Barlow Condensed", Arial, sans-serif',
    fontSize: '0.9375rem',
    fontWeight: 700,
    letterSpacing: '0.1em',
    textTransform: 'uppercase' as const,
  },
}
